schedules:
  adhoc:
    schedule: adhoc
os:
  - ubuntu/trusty64
java:
  - oraclejdk8
build:
  - script: |
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B install -DskipTests
