schedules:
  adhoc:
    schedule: adhoc
architecture:
  - x64
os:
  - ubuntu/xenial64
build:
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use openjdk8
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B install -DskipTests
